config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/en/rooms')
  scope "/:locale" do
    resources :rooms
    resources :services
    resources :categories
    resources :issues
    resources :feedbacks
    resources :orders
    resources :issues_managers
    resources :issues_manager_controllers
    resources :issues_managers
    devise_scope :user do
      get 'users/sign_out' => 'users/sessions#destroy'
    end
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }
    match 'issues_manager/:id/close' => 'issues#close', as: :issues_close, via: [:post, :get]
    match 'issues_manager/:id/proceed' => 'issues#proceed', as: :issues_proceed, via: [:post, :get]
    match 'issues/:id/mark_closed' => 'issues#mark_closed', as: :issues_mark_closed, via: [:post, :get]
    get :send_order_mail, to: 'rooms#send_order_mail', as: :send_order_mail
    resources :users
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :rooms do
    member do
      delete :delete_image_attachment
    end
  end
end

app/models/service.rb
class Service < ApplicationRecord
  validates :name, uniqueness: true, presence: true, format: { with: /\A[\-а-яА-ЯёЁІіЄєa-zA-Z\s]+\z/  },
            length: {maximum: 50, minimum: 2}
  validates :description, presence: false, length: {maximum: 100}
  validates :icon_url, presence: true

  has_many :room_services, dependent: :restrict_with_exception
  has_many :rooms, through: :room_services

  def destroyable?
    rooms.each do |room|
      return false if room.non_destroyable?
    end
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /services or /services.json
  def index
    @services = Service.paginate(:page => params[:page], :per_page => 4)
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /services/1 or /services/1.json
  def destroy
    if @service.destroyable?
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
      end
    else
      redirect_to services_url, notice: 'You cannot delete service with working orders'
    end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :description, :icon_url)
    end

  end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/prashantchaudhary/ddslick/master/jquery.ddslick.min.js" ></script>
<div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="
background: linear-gradient(rgba(0, 0, 0, 0.327),rgba(0, 0, 0, 0.5)),
  url(<%= asset_path 'main_8.jpg' %>) no-repeat center 70%;
  background-size: cover; height: 250px;
">
  <div class="mask mask-custom">
    <%if @service.new_record? %>
    <h1 class="display-4 fst-italic"><%= t("services.form.service_form_title") %></h1>
    <p class="lead my-3"><%= t('services.form.service_form_description') %></p>
      <% else  %>
      <h1 class="display-4 fst-italic"><%= t("services.edit.editing_service") %></h1>
      <p class="lead my-3"><%= t('services.edit.editing_service_desription') %></p>
      <% end %>
  </div>
</div>
<%= form_with(model: service, name: 'form' ) do |form| %>
  <% if service.errors.any? %>
    <div id="er" class="alert alert-danger" role="alert">
      <ul>
        <% service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="tbl">
    <div class="icon_field">
    <tr>
        <td><%= form.label :icon_url %></td>
        <td>
          <select id="icons">
            <% target_folder_path = File.join(Rails.root, "/app/assets/images/Icons") %>
            <% Dir.children(target_folder_path).sort.each do |icon| %>
              <option value="Icons/<%= icon %>" data-imagesrc="/assets/Icons/<%= icon %>"><%= icon %></option>
            <% end %>
          </select>
          <input type="hidden" id="service_icon_url" name="service[icon_url]" />
        </td>
      </tr>
    </div>
    <div class="name_field">
<tr>
    <td><%= form.label :name %></td>
  <td><%= form.text_field :name, placeholder: t('activerecord.attributes.service.placeholder_service_name')%></td>
</tr>
    </div>
    <div class="description-field">
    <tr>
    <td><%= form.label :description %></td>
    <td><%= form.text_area :description, placeholder: t('activerecord.attributes.service.placeholder_service_description')%></td>
    </tr>
    </div>
    <div class="button">
    <tr>
      <td></td>
      <% if @service.new_record? %>
      <td style="float: right;"><%= form.submit t('global.forms.create_button'), class: "btn btn-success text-white bottom-0 end-0", id: 'but', disabled: true%>&nbsp;<%= link_to t('global.forms.all_services') , services_path, class: 'btn btn-primary text-white bottom-0 end-0', role: 'button'%></td>
        <% else %>
        <td style="float: right;"><%= form.submit t('global.forms.update_button'), class: "btn btn-success text-white bottom-0 end-0", id: 'but', disabled: true%>&nbsp;<%= link_to t('global.forms.all_services') , services_path, class: 'btn btn-primary text-white bottom-0 end-0', role: 'button'%></td>
        <% end  %>
    </tr>
    </div>
    <%=  javascript_pack_tag 'dis_button', 'data-turbolinks-track': 'reload' %>
</table>

<% end %>

app/views/services/edit.html.erb
<%= render 'form', service: @service %>

app/views/services/index.html.erb
<div style="float: right; margin-top: 20px; margin-right: 20px;"><%= link_to t('.add_service'), new_service_path, class: 'btn btn-primary', role: 'button' %></div>
<div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="
background: linear-gradient(rgba(0, 0, 0, 0.327),rgba(0, 0, 0, 0.5)),
  url(<%= asset_path 'main_8.jpg' %>) no-repeat center 70%;
  background-size: cover; height: 250px;
">
  <div class="mask mask-custom">
    <h1 class="display-4 fst-italic"><%= t("services.index.services_title") %></h1>
    <p class="lead my-3"><%= t('services.index.services_description') %></p>
  </div>
</div>
<section>
  <div class="top-container">
  <% @services.each do |service| %>
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <div class="card" style="width: 23rem;">
          <div class="card-body text-center">
            <h5 class="card-title"><%= image_tag(service.icon_url, class: "col-2")%>&nbsp;<%= service.name %></h5>
            <p class="card-text"><%= service.description %></p>
            <div class="buttons_alignment">
              <div>
             <%= link_to t('.show_rooms'), service, class: 'btn btn-primary text-white bottom-0 end-0', role: 'button' %>
            <%= link_to t('.edit'), edit_service_path(service), class: 'btn btn-primary text-white bottom-0 end-0', role: 'button' %>
            <% if service.destroyable? %>
              <%= link_to t('.destroy'),service, method: :delete,  data: { confirm: 'Room services will be also deleted, continue?'}, role: 'button', class: 'btn btn-danger text-white bottom-0 end-0'%>
              <% else %>
                <div title="<%= t('.disabled_button_title')%>">
          <%= button_to t('.destroy'),service, method: :delete,  data: { confirm: 'Room services will be also deleted, continue?'}, disabled: true, class: 'btn btn-danger text-white bottom-0 end-0' %>
                </div>
              <% end  %>
              </div>

          </div>
          </div>
    </div>
        </div>
          <div class="col-md-4"></div>
      </div>
    <% end %>
      </div>
</section>
<div class="pagination" >
  <%= will_paginate @services, previous_label:  t('users.index.pagination.previous'), next_label: t('users.index.pagination.next'), list_classes: %w(pagination justify-content-end), :inner_window => 1, :outer_window => 1 %>
</div>

app/views/services/new.html.erb
<%= render 'form', service: @service %>

app/views/services/show.html.erb
    <div style="float: right; margin-top: 20px; margin-right: 20px;"><%= link_to t('global.forms.all_services'), services_path, class: 'btn btn-primary', role: 'button' %></div>
<div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="
background: linear-gradient(rgba(0, 0, 0, 0.327),rgba(0, 0, 0, 0.5)),
  url(<%= asset_path 'main_8.jpg' %>) no-repeat center 70%;
  background-size: cover; height: 250px;
">
  <div class="mask mask-custom">
    <h1 class="display-4 fst-italic"><%= t("services.show.show_service_title") %></h1>
    <p class="lead my-3"><%= t('services.show.description_show_service') %></p>
  </div>
</div>
<table class="tbl-2">
  <tr>
    <td><p class="h4"><%= t('services.show.icon_pic') %></p></td>
    <td><p class="h5"><%= image_tag(@service.icon_url)%></p></td>
  </tr>
  <tr>
    <td><p class="h4"><%= t('services.show.icon_url') %></p></td>
    <td><p class="h5"><%= @service.icon_url %></p></td>
  </tr>
<tr>
  <td><p class="h4"><%= t('services.show.name') %></p></td>
  <td><p class="h5"><%= @service.name %></p></td>
</tr>
<tr>
  <td><p class="h4"><%= t('services.show.service_description') %></p></td>
  <td><p class="h5"><%= @service.description %></p></td>
</tr>
</table>

<div class="row justify-content-center">
  <% if @service.rooms.empty? %>
    <h3 style="margin-top: 30px; color: red; text-align: center;"><%= t('services.show.there_are_no_rooms_using_this_service') %></h3>
    <% else %>
    <h3 style="margin-top: 30px; text-align: center;"><%= t('services.show.rooms_using_this_service') %></h3>
<div class="col-4">
  <table class="table table-hover" style="margin-top: 40px">
  <thead>
  <tr>
    <td class="h4">#</td>
    <td class="h4"><%= t('services.show.table.capacity') %></td>
    <td class="h4"><%= t('services.show.table.price') %></td>
    <td class="h4"><%= t('services.show.table.number') %></td>
  </tr>
  </thead>
<tbody>
  <% @service.rooms.uniq.each do |room| %>
      <tr>
        <th scope="row"><%= room.id %></th>
        <td class="h5"><%= room.capacity %></td>
        <td class="h5"><%= room.price %></td>
        <td class="h5"><%= room.number %></td>
      </tr>
    <% end  %>
</tbody>
</table>
</div>
    <% end %>
</div>