config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/en/rooms')
  scope "/:locale" do
    resources :rooms
    resources :services
    resources :categories
    resources :issues
    resources :feedbacks
    resources :orders
    resources :issues_managers
    resources :issues_manager_controllers
    resources :issues_managers
    devise_scope :user do
      get 'users/sign_out' => 'users/sessions#destroy'
    end
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }
    match 'issues_manager/:id/close' => 'issues#close', as: :issues_close, via: [:post, :get]
    match 'issues_manager/:id/proceed' => 'issues#proceed', as: :issues_proceed, via: [:post, :get]
    match 'issues/:id/mark_closed' => 'issues#mark_closed', as: :issues_mark_closed, via: [:post, :get]
    get :send_order_mail, to: 'rooms#send_order_mail', as: :send_order_mail
    resources :users
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :rooms do
    member do
      delete :delete_image_attachment
    end
  end
end

app/models/issue.rb
class Issue < ApplicationRecord
  enum status: %i[opened in_progress done]

  belongs_to :category
  belongs_to :user

  validates :text, presence: true
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: %i[ show edit update destroy ]
  # GET /issues or /issues.json
  def index
    @issues = Issue.all.order(:status).paginate(:page => params[:page], :per_page => 7)
    authorize! :read, Issue
  end

  # GET /issues/1 or /issues/1.json
  def show
    authorize! :read, Issue
  end

  # GET /issues/new
  def new
    @issue = Issue.new
    authorize! :create, Issue
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues or /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to issues_url, notice: t('.controller.issue_successfully_created') }
        format.json { render :index, status: :created, location: @issue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
    authorize! :create, Issue
  end

  def mark_closed
    issue = Issue.find(params[:id])
    respond_to do |format|
      format.html { redirect_to issues_url, notice: "Issue was successfully closed" }
      format.json { head :no_content }
    end

    issue.update_attribute('status', 2)

  end

  def close
    issue = Issue.find(params[:id])
    respond_to do |format|
      format.html { redirect_to issues_managers_url, notice: "You have changed issue status" }
      format.json { head :no_content }
    end

    issue.update_attribute('status', 2)

  end

  def proceed
    issue = Issue.find(params[:id])
    respond_to do |format|
      format.html { redirect_to issues_managers_url, notice: "You have changed issues status" }
      format.json { head :no_content }
    end
    issue.update_attribute('status', 1)
  end

  # PATCH/PUT /issues/1 or /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: "Issue was successfully updated." }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1 or /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: "Issue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_issue
    @issue = Issue.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def issue_params
    params.require(:issue).permit(:category_id, :user_id, :text, :status)
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="
background: linear-gradient(rgba(0, 0, 0, 0.327),rgba(0, 0, 0, 0.5)),
  url(<%= asset_path 'main_8.jpg' %>) no-repeat center 70%;
  background-size: cover; height: 250px;
">
  <div class="mask mask-custom">
    <h1 class="display-4 fst-italic"><%= t('issues._form.new_issue') %></h1>
    <p class="lead my-3"><%= t('issues.index.page_description') %></p>

  </div>
</div>
<div class="row justify-content-center">
  <div class="col-7">
    <div class="row justify-content-center">
      <div class="col-8 row justify-content-center">

        <%= form_with(model: issue) do |form| %>
          <% if issue.errors.any? %>
            <div id="error_explanation", class="alert alert-danger" role="alert">
              <ul>
                <% issue.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <br>

          <div class="btn-group">
            <%#= form.select :category_name, options_for_select(Category.all.names)%>
            <%= form.collection_select :category_id, Category.all, :id, :translated_name, :class => "select_name" %>
          </div>

          <div class="field">
            <%= form.text_area :category_description, :id => "description-field", :class => "alert alert-light",
                               :disabled => true %>
          </div>

          <div class="field">
            <%= form.hidden_field :user_id, :value => current_user.id %>
          </div>

          <div class="field">
            <%= form.text_area :text, :class => "issue-text" %>
          </div>

          <div class="field">
            <%= form.hidden_field :status %>
          </div>

          <div class="d-grid gap-3 d-md-flex justify-content-md-end">
            <%= form.submit t('issues._form.send'), class: "btn btn-success text-white bottom-0 end-0" %>
            <%= link_to t('issues._form.all_issues'), issues_path, class: "btn btn-primary text-white bottom-0 end-0" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    $(function () {
        category_names = [
            <% Category.all.each do |category| %>
            '<%= t("activerecord.attributes.category.descriptions.#{category.name}_description",
             :category_description => category.description) %>',
            <% end %>
        ]
        description_field = $('#description-field')
        name_field = $('#issue_category_id')
        name_field.on('change', function () {
            category_selected = parseInt(name_field[0].value)
            description_field[0].value = category_names[category_selected-1]

        })
        name_field.val('1')
        name_field.trigger('change')
    });

</script>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="
background: linear-gradient(rgba(0, 0, 0, 0.327),rgba(0, 0, 0, 0.5)),
  url(<%= asset_path 'main_8.jpg' %>) no-repeat center 70%;
  background-size: cover; height: 250px;
">
  <div class="mask mask-custom">
    <h1 class="display-4 fst-italic"><%= t("global.menu.issues") %></h1>
    <p class="lead my-3"><%= t('issues.index.page_description') %></p>

  </div>
</div>
<div class="row justify-content-center">
  <div class="col-7">
    <table class="table table-striped">
      <% if Issue.find_by_user_id(current_user.id).nil? %>
        <h1 class="display-4 fst-italic"> <%= t('.no_issues') %> </h1>
      <% else %>
        <thead>
        <tr>
          <th scope="col"><%= t('global.menu.categories') %></th>
          <th scope="col"><%= t('.text') %></th>
          <th scope="col"><%= t('.status') %></th>
          <th scope="col"><%= t('.created_at') %></th>
          <th scope="col"><%= t('.last_update') %></th>
          <th colspan="6"></th>
        </tr>
        </thead>

        <tbody>
        <tr>
          <% @issues.each do |issue| %>
            <% if issue.user == current_user %>
              <td><%= t("activerecord.attributes.category.names.#{Category.find(issue.category_id).name}") %></td>
              <td class="text-left"><%= issue.text %></td>
              <td>
                <% case issue.status
                   when 'opened' %>
                  <%= fa_icon "battery-empty lg", :title => 'just opened' %>
                <% when 'in_progress' %>
                  <%= fa_icon "battery-half lg", :title => 'in progress' %>
                <% when 'done' %>
                  <%= fa_icon "battery-full lg", :title => 'closed' %>
                <% end %>
              <td><%= issue.created_at.strftime t("time.datetime.formats.my_format") %></td>
              <td><%= issue.updated_at.strftime t("time.datetime.formats.my_format") %></td>
              <td>
                <% unless issue.status == 'done' %>
                  <%= link_to issues_mark_closed_path(:id => issue.id),
                              data: { confirm: 'Issue will be marked as closed. Continue?' },
                              :title => 'mark closed' do %>
                    <%= fa_icon "check-square lg" %>
                  <% end %>
                <% end %>
              </td>
            <% end %>
            </tr>
          <% end %>
      <% end %>
      </tbody>
    </table>
    <% if can? :create, Issue %>
      <div class="button_new_issue">
        <%= link_to t('.new_issue'), new_issue_path, class: "btn btn-primary text-white bottom-0 end-0 col-2" %>
      </div>
    <% end %>

  </div>
  <% unless Issue.find_by_user_id(current_user.id).nil? %>
    <div class="pagination-issues">
      <%= will_paginate @issues, :inner_window => 1, :outer_window => 1, previous_label: t('rooms.index.previous-button'), next_label: t('rooms.index.next-button') %>
    </div>
  <% end %>

</div>

app/views/issues/new.html.erb
<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @issue.category_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @issue.user_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @issue.text %>
</p>

<p>
  <strong>Status:</strong>
  <%= @issue.status %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>