config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/en/rooms')
  scope "/:locale" do
    resources :rooms
    resources :services
    resources :categories
    resources :issues
    resources :feedbacks
    resources :orders
    resources :issues_managers
    resources :issues_manager_controllers
    resources :issues_managers
    devise_scope :user do
      get 'users/sign_out' => 'users/sessions#destroy'
    end
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }
    match 'issues_manager/:id/close' => 'issues#close', as: :issues_close, via: [:post, :get]
    match 'issues_manager/:id/proceed' => 'issues#proceed', as: :issues_proceed, via: [:post, :get]
    match 'issues/:id/mark_closed' => 'issues#mark_closed', as: :issues_mark_closed, via: [:post, :get]
    get :send_order_mail, to: 'rooms#send_order_mail', as: :send_order_mail
    resources :users
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :rooms do
    member do
      delete :delete_image_attachment
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :number, format: { with: /\A[\-а-яА-ЯёЁІіЇїЄєa-zA-Z0-9\s]+\z/ }, length: {maximum: 10, minimum: 2}, presence: true, uniqueness: true
  validates :title, length: {minimum: 2, maximum: 25}, presence: true
  validates :capacity, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 3 }, presence: true
  validates :price, format: {with: /\A[0-9]+.*[0-9]*\z/}, presence: true
  validate :acceptable_cover
  validate :acceptable_images
  has_many :orders
  has_many :room_services, dependent: :restrict_with_exception
  has_many :services, through: :room_services
  has_one_attached :cover
  has_many_attached :images

  def destroyable?
    orders.each do |order|
       status = order.status
      return false if status != 'cancelled' && status != 'completed'
    end
  end

  def non_destroyable?
    !destroyable?
  end

  def acceptable_cover
    return if !cover.attached?
    # errors.add(:cover, :count) if cover.id.nil?
    errors.add(:cover, :size) if cover.byte_size  > 2.megabyte

    acceptable_types = ["image/jpeg", "image/png", "image/jpg"]
    errors.add(:cover, :format) if !acceptable_types.include?(cover.content_type)
  end

  def acceptable_images
    return if !images.attached?

    errors.add(:images, :count) if images.count > 4
    acceptable_types = ["image/jpeg", "image/png", "image/jpg"]
    images.each do |image|
      errors.add(:images, :size) if image.byte_size  > 2.megabyte
      errors.add(:images, :format) if !acceptable_types.include?(image.content_type)

    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]
  # GET /rooms or /rooms.json
  def index
    per_page = 2
    @q = Room.ransack(
      sorts: params.fetch(:q, nil)&.fetch(:sorts, nil),
      m: 'or',
      g: {
        '0' => {
          capacity_eq: params.fetch(:q, nil)&.fetch(:capacity_eq, nil),
          price_gteq: params.fetch(:q, nil)&.fetch(:price_gteq, nil),
          price_lteq: params.fetch(:q, nil)&.fetch(:price_lteq, nil),
          m: 'and',
          g: {
            '0' => {
              orders_check_out_not_eq: params.fetch(:q, nil)&.fetch(:orders_check_out_gt, nil),
            },
            '1' => {
              orders_check_in_not_eq: params.fetch(:q, nil)&.fetch(:orders_check_in_lt, nil)
            }
          }
        },
        '1' => { orders: [nil, ""] }
      })

    @rooms = @q.result(:distinct=>true).paginate(:page => params[:page], :per_page => per_page)
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @room = Room.find(params[:id])
    @order = Order.new
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        params[:room][:service_ids].each do |service_id|
          unless service_id.empty?
            service = Service.find(service_id)
            @room.services << service
          end
        end
        format.html { redirect_to new_room_url, notice: "Room was successfully created"}
        format.json { render :show, status: :created, location: @room }

      else

        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to edit_room_url, notice: "Room was successfully updated" }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    if @room.destroyable?
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
    else
      redirect_to rooms_url, notice: 'You cannot delete room with working orders'
    end
  end
  def delete_image_attachment
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge
    redirect_back(fallback_location: rooms_path, notice: "Photo was successfully deleted")
  end
  private

    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:capacity, :price, :number, :title,  :cover, images: [], service_ids: [] )
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def check_in_date
    date = params.fetch(:q, nil)&.to_unsafe_h&.fetch(:orders_check_in_lt, nil)
    (date.present? ? Date.parse(date) : Date.current).strftime('%m/%d/%Y')
  end

  def check_out_date
    date = params.fetch(:q, nil)&.to_unsafe_h&.fetch(:orders_check_out_gt, nil)
    (date.present? ? Date.parse(date) : Date.current).strftime('%m/%d/%Y')
  end
end

app/views/rooms/_form.html.erb
<script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
<link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
<div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="
background: linear-gradient(rgba(0, 0, 0, 0.327),rgba(0, 0, 0, 0.5)),
  url(<%= asset_path 'main_8.jpg' %>) no-repeat center 70%;
  background-size: cover; height: 250px;
">
  <div class="mask mask-custom">
    <%if @room.new_record? %>
      <h1 class="display-4 fst-italic"><%= t("rooms.form.room_form_title") %></h1>
      <p class="lead my-3"><%= t('rooms.form.room_form_description') %></p>
    <% else  %>
      <h1 class="display-4 fst-italic"><%= t("rooms.form.room_form_title_edit") %></h1>
      <p class="lead my-3"><%= t('rooms.form.room_form_title_description') %></p>
    <% end %>
  </div>
</div>
<%=  form_with model: @room do |form| %>
  <% if @room.errors.any? %>
    <div id="er" class="alert alert-danger" role="alert" style="height: 250px; width: 500px;">
      <ul>
        <% @room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<table class="tbl" style="margin-top: 30px;">
  <tr>
  <div class="field">
    <td><%= form.label :number %></td>
    <td><%= form.text_field :number %></td>
  </div>
  </tr>
  <tr>
 <div class="field">
   <td><%= form.label :title %></td>
   <td><%= form.text_field :title %></td>
 </div>
  </tr>
  <tr>
  <div class="field">
    <td><%= form.label :capacity %></td>
    <td><%= form.text_field :capacity %></td>
  </div>
  </tr>
  <tr>
  <div class="field">
    <td><%= form.label :price %></td>
    <td><%= form.text_field :price %></td>
  </div>
  </tr>
  <tr>
  <tr>
    <div class="field">
      <td><label for="services"><%= t('activerecord.attributes.room.services') %></label></td>
      <td><input type="text" id="services" name="services" autocomplete="off"></td>
    </div>
  </tr>
  <div id="my-dialog">
    <dialog id="dialog_window">
      <img src="/assets/exit_button.png" id="close">
      <%= collection_check_boxes(:room, :service_ids, Service.all, :id, :name, {}) do |b| %>
        <div class="checkbox" style="display: block;">
          <%= b.check_box %>
          <%= image_tag(b.object.icon_url) %>
          <%= b.label class:'labels' %>
        </div>
      <% end %>
    </dialog>
  </div>
    <%=  javascript_pack_tag 'dialog_window_service', 'data-turbolinks-track': 'reload' %>
  <tr>
    <div class="field">
      <td><%= form.label :cover %></td>
      <td><div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-max-files="1" >
        <%= form.file_field :cover, direct_upload: true, data: { target: 'dropzone.input' } %>
        <% if !@room.cover.attached?%>
        <div class="dropzone-msg dz-message needsclick" >
          <h3 class="dropzone-msg-title" style="font-size: 1.2em; text-align: center;"><%= t('activerecord.attributes.room.drag_here_or_click') %></h3>
          <span class="dropzone-msg-desc text-sm"><%=t('activerecord.attributes.room.allowed_types_cover')  %></span>
        </div>
          <% else %>
          <div class="dropzone-msg dz-message needsclick" >
            <h3 class="dropzone-msg-title" style="font-size: 1.2em; text-align: center;"><%= t('activerecord.attributes.room.if_cover_attached') %></h3>
            <span class="dropzone-msg-desc text-sm"><%=t('activerecord.attributes.room.allowed_types_cover')  %></span>
          </div>
          <% end %>

      </div></td>
    </div>
  </tr>
  <tr>
    <div class="field">
      <td><%= form.label :images %></td>
      <td><div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-max-files="4">
        <%= form.file_field :images, direct_upload: true, data: { target: 'dropzone.input' }, multiple: true%>
        <% if !@room.images.attached?%>
        <div class="dropzone-msg dz-message needsclick" >
          <h3 class="dropzone-msg-title" style="font-size: 1.2em; text-align: center;"><%= t('activerecord.attributes.room.drag_here_or_click') %></h3>
          <span class="dropzone-msg-desc text-sm"><%=t('activerecord.attributes.room.allowed_types')  %></span>
        </div>
          <% else %>
          <div class="dropzone-msg dz-message needsclick" >
            <h3 class="dropzone-msg-title" style="font-size: 1.2em; text-align: center;"><%= t('activerecord.attributes.room.drag_here_or_click_if_attached') %></h3>
            <span class="dropzone-msg-desc text-sm"><%=t('activerecord.attributes.room.allowed_types')  %></span>
          </div>
          <% end %>
      </div></td>
    </div>
  </tr>
  <tr>
  <div class="actions">
    <td></td>
    <% if @room.new_record? %>
      <td style="float: right;"><%= form.submit t('rooms.form.create_room'), class: "btn btn-success text-white bottom-0 end-0", id: 'but'%>&nbsp;<%= link_to t('rooms.form.all_rooms') , rooms_path, class: 'btn btn-primary text-white bottom-0 end-0', role: 'button'%></td>
    <% else %>
      <td style="float: right;"><%= form.submit t('rooms.form.update_room'), class: "btn btn-success text-white bottom-0 end-0", id: 'but'%>&nbsp;<%= link_to t('rooms.form.all_rooms') , rooms_path, class: 'btn btn-primary text-white bottom-0 end-0', role: 'button'%></td>
    <% end %>
  </div>
  </tr>
</table>
<% end %>
<% if !@room.new_record? %>
<% if @room.cover.attached?%>
    <h4 id="main-image-edit">Main image:</h4>
<div class="uploaded-cover">
  <% if  !@room.cover.id.nil? %>
  <div style="display: inline-block;">
  <div><%= image_tag @room.cover, size: "200x100" %></div>
  <div style="align-items: center;">
    <%= link_to t('activerecord.attributes.room.remove'), delete_image_attachment_room_url(@room.cover.id), method: :delete, data: { confirm: 'The photo will be permanently deleted, continue?' }, role: 'button'%>
  </div>
  </div>
  <% end  %>
</div>
  <% else %>
  <div class="no-uploaded-cover">
    <h4><%= t('activerecord.attributes.room.no_cover_attached') %></h4>
  </div>
<% end %>
<% if @room.images.attached? %>
    <h4 id="images-edit">Photos:</h4>
<div class="uploaded-images" style="float: right; margin-top: -400px; margin-right: 15px;">
  <% @room.images.each do |image| %>
    <% unless image.id.nil? %>
    <div style="display: inline-block;">
    <div><%= image_tag image, class: "room_images_in_edit" %></div>
    <div><%= link_to t('activerecord.attributes.room.remove'), delete_image_attachment_room_url(image.id), method: :delete, data: { confirm: 'The photo will be permanently deleted, continue?' }%></div>
    </div>
      <% end %>
    <% end  %>
</div>
  <% else %>
  <div class="no-uploaded-images">
    <h4><%= t('activerecord.attributes.room.no_photos_attached') %></h4>
  </div>
<% end %>
<% end %>

app/views/rooms/edit.html.erb
<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<div class="rooms-top-container">
  <% if can? :manage, Room %>
  <div style="float: right; margin-top: 20px; margin-right: 20px;"><%= link_to t('rooms.index.add_room'), new_room_path, class: "btn btn-primary text-white bottom-0 end-0", role: 'button' %></div>
  <% end %>
  <div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="
  background: linear-gradient(rgba(0, 0, 0, 0.327),rgba(0, 0, 0, 0.5)),
    url(<%= asset_path 'main_8.jpg' %>) no-repeat center 70%;
    background-size: cover; height: 250px;
  ">
    <div class="mask mask-custom">
      <h1 class="display-4 fst-italic"><%= t('rooms.index.page-title') %></h1>
      <p class="lead my-3"><%= t('rooms.index.page-description') %></p>

    </div>
  </div>
</div>
<%= search_form_for @q do |f| %>
  <div class= "advance-search-container">
    <div class="search-input">
      <p><%= t('rooms.index.search.check-in-out') %></p>
      <input id="input-datepicker" class="search-form-input">
    </div>

    <%= f.date_field :orders_check_out_gt, class: 'search-form-input date-input', id: 'check-out-input', :value => Time.now.strftime('%Y-%m-%d') %>
    <%= f.date_field :orders_check_in_lt, class: 'search-form-input date-input', id: 'check-in-input', :value => Time.now.strftime('%Y-%m-%d') %>

    <div class="search-input">
      <p><%= f.label :capacity, t('rooms.index.search.capacity') %></p>
      <%= f.select :capacity_eq,
                   options_for_select(Room.all.order(:capacity => :asc).map {|p| [ p.capacity ]}.uniq,
                                      selected: params.fetch(:q, nil)&.fetch(:capacity_eq, nil)), {:include_blank => t('rooms.index.search.choose')},
                   { :class => 'search-form-capacity' } %>
    </div>

    <div class="search-input">
      <p><%= f.label :price, t('rooms.index.search.price-from') %></p>
      <%= f.number_field :price_gteq, min: Room.minimum(:price), max: Room.maximum(:price), class: 'search-form-input' %>
    </div>

    <div class="search-input">
      <p><%= f.label :price, t('rooms.index.search.price-to') %></p>
      <%= f.number_field :price_lteq, min: Room.minimum(:price), max: Room.maximum(:price), class: 'search-form-input' %>
    </div>

    <div class="advance-search-button">
      <%= f.submit t('rooms.index.search.submit'), class: 'btn btn-primary', id: 'search-button' %>
    </div>

      <div class="advance-search-button">
        <%= button_to t('rooms.index.search.clear-filters'), rooms_path,
                      :class => "btn btn-primary clear-filters", :method => :get %>
      </div>
  </div>

    <div class="sort-container">
      <% unless @rooms.size < 2 %>
        <%= f.select :sorts,
                 options_for_select(
                   [[t('rooms.index.search.low-high'), 'price asc'],
                    [t('rooms.index.search.high-low'), 'price desc']],
                   selected: params.fetch(:q, nil)&.fetch(:sorts, nil)),
                 {:include_blank => t('rooms.index.search.sort-by')},
                 { :class => 'sort-input', :id => 'sort-input' } %>
      <% end %>
    </div>
  <div class="container">
    <% if @rooms.empty? %>
      <p class="lead my-3 text-center"><%= t('rooms.index.no-rooms') %></p>
    <% else %>
      <% @rooms.each do |room| %>
        <div class="card mb-8">
          <%= image_tag room.cover, class: "card-img-top" if room.cover.attached?   %>
          <div class="card-body ">
            <h5 class="card-title"><%= room.title %></h5>
            <p class="card-text"><%= t('rooms.index.label-before-capacity')%> <%= room.capacity %> <%= t('rooms.index.label-after-capacity')%></p>
            <div class="card_footer justify-content-between">
              <span class="d-block">
                <span class="display-4 text-primary">$<%= room.price %></span> / <%= t('rooms.index.per-night') %>
              </span>
              <div class="buttons_alignment">
                <%= link_to t('rooms.index.show-more'), room_path(room, :check_in => params.fetch(:q, nil)&.fetch(:orders_check_in_lt, nil), :check_out => params.fetch(:q, nil)&.fetch(:orders_check_out_gt, nil)), :class => "btn btn-primary text-white bottom-0 end-0" %>
                <% if can? :manage, Room %>
                <div><%= link_to t('rooms.index.edit_room'), edit_room_path(room), :class => "btn btn-primary text-white bottom-0 end-0" %></div>
                <% if room.destroyable? %>
                  <div><%= button_to t('rooms.index.destroy_room'), room, method: :delete,  data: { confirm: 'Room services will be also deleted, continue?'}, class: 'btn btn-danger text-white bottom-0 end-0'%></div>
                <% else %>
                  <div title="<%= t('rooms.index.disabled_title') %>">
                    <%= button_to t('rooms.index.destroy_room'), room, method: :delete,  data: { confirm: 'Room services will be also deleted, continue?'}, disabled: true, class: 'btn btn-danger text-white bottom-0 end-0' %>
                  </div>
                    <% end %>
                <% end  %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    </div>
  <% end %>
    </ul>
<% end %>

<div class="pagination" >
  <%= will_paginate @rooms, previous_label: t('rooms.index.previous-button'), next_label: t('rooms.index.next-button'), list_classes: %w(pagination justify-content-end), :inner_window => 1, :outer_window => 1 %>
</div>

<script>
  $('#input-datepicker').daterangepicker({
      opens: 'left',
      startDate: '<%= check_in_date %>',
      endDate: '<%= check_out_date %>',
  }, function(start, end, label) {

      $('#check-in-input').val(start.format('YYYY-MM-DD'));
      $('#check-out-input').val(end.format('YYYY-MM-DD'));
      $('#input-datepicker').val(`${start.format('MM/DD/YYYY')} - ${end.format('MM/DD/YYYY')}`);
  });
</script>

app/views/rooms/new.html.erb
<%= render 'form', room: @room %>

app/views/rooms/room_send.text.erb
Hello from hotel!

app/views/rooms/show.html.erb
<div class="room-top-container">
  <div class="bg-image p-5 text-center shadow-1-strong text-white" style="
      background: linear-gradient(rgba(0, 0, 0, 0.327),rgba(0, 0, 0, 0.5)),
        url(<%= url_for(@room.cover) if @room.cover.attached? %>) no-repeat center 70%;
        background-size: cover; height: 250px;
      ">
    <div class="mask mask-custom" style="">
      <h1 class="display-4 fst-italic"><%= t('rooms.show.room') %> <%= @room.number %></h1>
      <p class="lead my-3"><%= t('rooms.show.description') %></p>
    </div>
  </div>
</div>

<%= link_to t('rooms.show.back-button'), rooms_path, :class => "btn btn-primary text-white back" %>

<div class="room-images">
  <div class="row">
    <% @room.images.each do |image| if @room.images.attached? %>
      <div class="room-image col-lg-3 col-md-4 col-6">
        <%= image_tag image, class: "img-fluid" %>
      </div>
    <% end %>
      <% end  %>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @room.title %></h5>

    <p class="card-text">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
        <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
        <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
        <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
      </svg>
      <%= t('rooms.show.capacity') %>: <%= @room.capacity %>
    </p>

    <% if @room.services.empty? %>
      <p class="card-text">No services are implied.</p>
    <% else %>
      <p class="card-text">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
          <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
        </svg>
        <%= t('rooms.show.services') %>:
      </p>
      <ul class="list-group">
        <% @room.services.each do |service| %>
          <li class="list-group-item borderless">
            <img class="service-icon" alt="service icon" src=<%= asset_path(service.icon_url)%>>
            <span class="card-text">
              <%=  link_to service.name, service.description, {:class => "link"} %>
            </span>
          </li>
        <% end %>
      </ul>
    <% end %>

    <% unless params[:check_in].present? && params[:check_out].present? %>
      <span class="card-text"><%= t('rooms.show.no-dates') %></span>
    <% end %>

    <div class="card_footer">
          <span class="d-block">
            <span class="display-4 text-primary">$<%= @room.price %></span>
            / <%= t('rooms.show.per-night') %>
          </span>
      <div class="card-footer-button col-md-3">
        <% if user_signed_in? %>
          <% if params[:check_in].present? && params[:check_out].present? %>
            <button type="button" class="btn btn-primary text-white bottom-0 end-0" data-bs-toggle="modal" data-bs-target="#bookingModal">
              <%= t('rooms.show.book-now') %>
            </button>
          <% else %>
            <button type="button" class="btn btn-primary text-white bottom-0 end-0 disabled">
              <%= t('rooms.show.book-now') %>
            </button>
          <% end %>
        <% else %>
          <%= link_to t('rooms.show.book-now'), new_user_registration_path, class: "btn btn-primary text-white bottom-0 end-0" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="bookingModal" tabindex="-1" aria-labelledby="bookingModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title card-text" id="bookingModalLabel"><%= t('rooms.show.modal.title') %>:</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p class="card-text"><%= t('rooms.show.modal.check-in') %>: <span id="check-in"><%= params[:check_in] %></span> </p>
          <p class="card-text"><%= t('rooms.show.modal.check-out') %>: <span id="check-out"><%= params[:check_out] %></span> </p>
          <p class="card-text"><%= t('rooms.show.modal.room-type') %>: <%= @room.title %></p>
          <p class="card-text"><%= t('rooms.show.capacity') %>: <%= @room.capacity %></p>
          <p class="card-text"><%= t('rooms.show.modal.price-per-night') %>: <span id="price-per-night"><%= @room.price %></span>$</p>
          <p class="card-text"><%= t('rooms.show.modal.total-price') %>: <span id="total-price"></span>$</p>
          <p class="card-text"><%= t('rooms.show.modal.confirmation-label') %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><%= t('rooms.show.modal.cancel') %></button>
          <% if user_signed_in? %>
            <%= form_for @order do |f| %>
              <%= f.hidden_field :check_in, :value => params[:check_in] %>
              <%= f.hidden_field :check_out, :value => params[:check_out] %>
              <%= f.hidden_field :total_price, :id => "total-price-input", :value => 22 %>
              <%= f.hidden_field :room_id, :value => @room.id %>
              <%= f.hidden_field :user_id, :value => current_user.id%>
              <%= f.hidden_field :status, :value => 'processed' %>
              <%= f.submit t('rooms.show.modal.submit'), :class => "btn btn-primary", :id => "submit-booking-btn" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
</div>

<script>
  const totalPriceElem = document.getElementById("total-price");
  const checkInElem = document.getElementById("check-in");
  const checkOutElem = document.getElementById("check-out");
  const pricePerNight = document.getElementById("price-per-night").innerText;
  const totalPriceInputElem = document.getElementById("total-price-input");
  const submitBookingBtn = document.getElementById("submit-booking-btn");

  if (checkInElem && checkOutElem) {
     const start = new Date(checkInElem.innerText);
     const end = new Date(checkOutElem.innerText);
     const timeDiff = Math.abs(end.getTime() - start.getTime());
     const numberOfNights = Math.ceil(timeDiff / (1000 * 3600 * 24));
     const totalPrice = Math.round(numberOfNights * pricePerNight * 100) / 100;
     totalPriceElem.innerText = totalPrice;
     totalPriceInputElem.value = totalPrice;
  }
</script>