config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/en/rooms')
  scope "/:locale" do
    resources :rooms
    resources :services
    resources :categories
    resources :issues
    resources :feedbacks
    resources :orders
    resources :issues_managers
    resources :issues_manager_controllers
    resources :issues_managers
    devise_scope :user do
      get 'users/sign_out' => 'users/sessions#destroy'
    end
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }
    match 'issues_manager/:id/close' => 'issues#close', as: :issues_close, via: [:post, :get]
    match 'issues_manager/:id/proceed' => 'issues#proceed', as: :issues_proceed, via: [:post, :get]
    match 'issues/:id/mark_closed' => 'issues#mark_closed', as: :issues_mark_closed, via: [:post, :get]
    get :send_order_mail, to: 'rooms#send_order_mail', as: :send_order_mail
    resources :users
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :rooms do
    member do
      delete :delete_image_attachment
    end
  end
end

app/models/category.rb
# frozen_string_literal: true
class Category < ActiveRecord::Base
  validates :name, uniqueness: { case_sensitive: false }
  validates :description, length: { maximum: 150 }, format: { with: /\A\D([A-z0-9])/,
                                                              message: 'should not start from a digit' },
                          allow_blank: true
  has_many :issues
  enum name: [:Urgent, :Breakage, :Advice, :Other]

  def translated_name
    I18n.t(name, :scope => 'activerecord.attributes.category.names')
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  load_and_authorize_resource
  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show_hidden, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated!' }
        format.json { render :show_hidden, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
    # respond_to do |format|
    #   if @category.update(category_params)
    #     format.html { redirect_to @category, notice: "Category was successfully updated." }
    #     format.json { render :show_hidden, status: :ok, location: @category }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @category.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="
background: linear-gradient(rgba(0, 0, 0, 0.327),rgba(0, 0, 0, 0.5)),
  url(<%= asset_path 'main_8.jpg' %>) no-repeat center 70%;
  background-size: cover; height: 250px;
">
  <div class="mask mask-custom">
      <h1 class="display-4 fst-italic"><%= t("categories.edit.editing_category_title") %></h1>
      <p class="lead my-3"><%= t("categories.edit.editing_category_description")%></p>
  </div>
</div>
  <div class="row justify-content-center">
  <div class="col-5">
    <% if notice.present? %>
      <!--      <p id="notice" class="alert alert-success"><%#= notice %></p>-->
    <% end %>
    <%= form_with(model: category) do |form| %>
      <% if category.errors.any? %>
        <div id="error_explanation" class="alert alert-danger" role="alert">
          <ul>
            <% category.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row justify-content-center">
        <div class="col-12 row justify-content-center">
          <form class="form-group">
            <div class="form-group row col-md-12">
              <%= form.label :name, class: "col-sm-3 col-form-label" %>
              <div class="col-sm-12">
                <%= form.text_field :name, disabled: true, class: "form-control", type: "text" %>
              </div>
            </div>
            <div class="form-group row col-md-12">
              <%= form.label :description, class: "col-sm-3 col-form-label" %>
              <div class="col-sm-12">
                <%= form.text_area :description, class: "form-control", type: "text" %>
                <br>
              </div>
            </div>
            <div class="form-group row col-md-12">
              <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <%= form.submit t('global.forms.update_button'), class: "btn btn-success" %>
                <%= link_to t('global.forms.all_categories'), categories_path, class: "btn btn-primary" %>
              </div>
            </div>
          </form>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="
background: linear-gradient(rgba(0, 0, 0, 0.327),rgba(0, 0, 0, 0.5)),
  url(<%= asset_path 'main_8.jpg' %>) no-repeat center 70%;
  background-size: cover; height: 250px;
">
  <div class="mask mask-custom">
    <h1 class="display-4 fst-italic"><%= t(".category") %></h1>
    <p class="lead my-3"><%= t('issues.index.page_description') %></p>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-7">

    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col"><%= t("activerecord.attributes.category.name") %></th>
        <th scope="col"><%= t("activerecord.attributes.category.description") %></th>
        <th scope="col"></th>
      </tr>
      </thead>

      <tbody>
      <tr>
        <% @categories.each do |category| %>
          <td><%= category.name %></td>
          <td class="text-left"><%= category.description %></td>
          <td><%= link_to edit_category_path(category), :title => 'Edit' do %>
              <%= fa_icon "pencil 2x" %>
            <% end %>
          </td>
          </tr>
        <% end %>
        </tbody>
    </table>
  </div>
</div>

<br>

<%#= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to t('global.forms.back_button'), categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to t('global.forms.edit_button'), edit_category_path(@category) %> |
<%= link_to t('global.forms.back_button'), categories_path %>